import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://localhost:3000';
let cookie='',rev=0,workspace;
async function call(op,extra={},expected=200){const r=await fetch(`${base}/api/workspace`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,Origin:base},body:JSON.stringify({op,revision:rev,...extra})});const d=await r.json();assert.equal(r.status,expected,JSON.stringify(d));if(r.status===200){cookie=r.headers.get('set-cookie').split(';')[0];rev=d.revision;workspace=d.workspace;}return d;}
await call('demo');assert.equal(workspace.mode,'demo');
await call('plan',{},400);
const findings=workspace.findings.map(f=>({...f,status:'confirmed'}));findings[0].value='Bookkeeping for independent architecture studios.';findings[0].status='corrected';
await call('calibrate',{findings,goal:'5 qualified conversations in 30 days',budget:'4 hours and $100',notes:'No paid ads.'});
await call('plan');assert.equal(workspace.channels.length,5);
await call('run',{channel:'outreach'});assert.match(workspace.channels[0].artifact,/architecture studios/);assert.equal(workspace.channels[0].status,'needs_owner');
await call('run',{channel:'outreach'},400);
await call('run',{channel:'partners'});
await call('run',{channel:'content'},400);
await call('result',{channel:'outreach',result:5},400);
await call('handoff',{channel:'outreach',evidence:'x'},400);
await call('handoff',{channel:'outreach',evidence:'TEST ONLY: simulated owner action log; no messages sent.'});
await call('result',{channel:'outreach',result:-1},400);
await call('result',{channel:'outreach',result:2});assert.equal(workspace.channels[0].status,'reviewed');assert.match(workspace.channels[0].learning,/Below target/);
await call('run',{channel:'content'});
const saved=await (await fetch(`${base}/api/workspace`,{headers:{Cookie:cookie}})).json();assert.equal(saved.revision,rev);assert.equal(saved.workspace.channels[0].result,2);
const other=await (await fetch(`${base}/api/workspace`)).json();assert.equal(other.workspace,null);
await call('demo',{revision:0},409);
await call('research',{url:'https://example.com'},400);
const badOrigin=await fetch(`${base}/api/workspace`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,Origin:'https://unrelated.example'},body:JSON.stringify({op:'demo',revision:rev})});assert.equal(badOrigin.status,403);
console.log('PASS: calibration, corrected draft context, 5 channels, state transitions, 2-experiment limit, handoffs, results, persistence, session isolation, stale writes, missing live key, origin protection.');
