'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, Compass, FlaskConical, Globe, Hand, Layers, LoaderCircle, Radar, Sparkles, Download, CircleDot, KeyRound } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import type { Workspace, Finding } from '@/lib/engine';
type ApiResponse = {workspace:Workspace|null;revision:number;error?:string};
const stages=['Research','Calibration','Channels','Experiments'];
export default function Home(){
 const [w,setW]=useState<Workspace|null>(null),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('Research'),[url,setUrl]=useState(''),[key,setKey]=useState(''),[showKey,setShowKey]=useState(false),[findings,setFindings]=useState<Finding[]>([]),[goal,setGoal]=useState(''),[budget,setBudget]=useState(''),[notes,setNotes]=useState(''),[evidence,setEvidence]=useState<Record<string,string>>({}),[results,setResults]=useState<Record<string,string>>({}),[showNew,setShowNew]=useState(false);
 function accept(data:{workspace:Workspace|null;revision:number}){setW(data.workspace);setRevision(data.revision);if(data.workspace){setFindings(data.workspace.findings);setGoal(data.workspace.goal);setBudget(data.workspace.budget);setNotes(data.workspace.notes);}}
 useEffect(()=>{fetch('/api/workspace').then(async r=>{if(!r.ok)throw Error('Could not load your workspace. Please reload.');return r.json() as Promise<ApiResponse>;}).then(accept).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function act(op:string,extra:Record<string,unknown>={},next?:string){setBusy(op);setError('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,revision,key,...extra})});const data=await r.json() as ApiResponse;if(!r.ok)throw Error(data.error||'Something went wrong. Retry.');accept(data);setShowNew(false);if(next)setTab(next);}catch(e){setError(e instanceof Error?e.message:'Could not complete the action.');}finally{setBusy('');}}
 function download(name:string,content:string){const u=URL.createObjectURL(new Blob([content],{type:'text/markdown'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u);}
 const waiting=w?.channels.filter(c=>c.status==='needs_owner')||[]; const active=w?.channels.filter(c=>c.status!=='suggested')||[];
 const setup=<section className="setup">{w&&<p className="demo-banner">Starting new research replaces this browser’s current workspace. Export it first if you want to keep a copy.</p>}<div className="setup-icon"><Radar size={30}/></div><p className="eyebrow">YOUR NEXT GROWTH EXPERIMENT STARTS HERE</p><h1>First, let’s understand<br/>the business.</h1><p className="muted intro">Start with its website. Then correct the research, choose your channels, and put the first experiment to work.</p><form onSubmit={e=>{e.preventDefault();act('research',{url},'Research');}}><label htmlFor="website">Business website</label><div className="url-row"><Globe size={18}/><Input id="website" type="url" required placeholder="https://your-business.com" value={url} onChange={e=>setUrl(e.target.value)}/><Button disabled={!!busy||!key} type="submit">Research business <ArrowRight size={16}/></Button></div></form><p className="small muted">{key?'Live research uses your OpenAI API account.':'Connect an API key above to research a real business.'}</p><div className="demo-row"><div><strong>Take it for a test run</strong><p className="small muted">A fictional bookkeeping studio. The complete workflow.</p></div><Button variant="outline" disabled={!!busy} onClick={()=>act('demo',{},'Research')}>Try the demo <ArrowUpRight size={16}/></Button></div>{w&&<Button variant="ghost" onClick={()=>setShowNew(false)}>Back to current workspace</Button>}</section>;
 return <div className="app-shell"><header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Layers size={21}/></span>traction<span className="mvp">LAB</span></a><div className="top-actions"><span className="private">Private workspace</span><Button variant="outline" size="sm" onClick={()=>setShowKey(!showKey)}><KeyRound size={15}/>{key?'AI connected for this session':'Connect AI'}</Button></div></header>
 {showKey&&<section className="connection"><div><strong>Connect live research & drafting</strong><p className="small muted">Your key stays in memory for this tab and is sent only to this app’s server for OpenAI requests. It is not saved. Usage is billed to your API account.</p></div><label className="sr-only" htmlFor="key">OpenAI API key</label><Input id="key" type="password" autoComplete="off" placeholder="OpenAI API key" value={key} onChange={e=>setKey(e.target.value)}/><Button variant="outline" onClick={()=>{setKey('');setShowKey(false);}}>Disconnect</Button><Button onClick={()=>setShowKey(false)}>Done</Button></section>}
 <main>{error&&<div className="error" role="alert">{error}<Button variant="ghost" size="sm" onClick={()=>setError('')}>Dismiss</Button></div>}{busy&&<div className="working" role="status"><LoaderCircle className="spin" size={17}/>{busy==='research'?'Researching the business and public sources. This may take a minute…':busy==='plan'?'Evaluating channels against your calibrated brief…':busy==='run'?'Creating the experiment asset…':'Saving your work…'}</div>}
 {loading?<div className="setup muted">Loading your workspace…</div>:(!w||showNew)?setup:<>
 <div className="workspace-heading"><div><p className="eyebrow">GROWTH WORKSPACE <span className="slash">/</span> {w.mode==='demo'?'FICTIONAL DEMO':'LIVE RESEARCH'}</p><h1>{w.name}</h1><p className="muted">{w.url.replace(/^https?:\/\//,'')}<span className="dot">·</span>{w.calibrated?'Owner calibration complete':'Getting to know your business'}</p></div><Button variant="outline" onClick={()=>setShowNew(true)}>New research <ArrowUpRight size={16}/></Button></div>
 {w.mode==='demo'&&<div className="demo-banner"><FlaskConical size={17}/><span>Demo workspace · Fictional research and template drafts. Nothing is sent or published.</span></div>}
 <div className="workspace-grid"><section className="workspace-main"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="stage-tabs" variant="line">{stages.map((s,i)=><TabsTrigger key={s} value={s}><span className="step-number">0{i+1}</span>{s}{s==='Experiments'&&active.length>0&&<span className="count">{active.length}</span>}</TabsTrigger>)}</TabsList>
 <TabsContent value="Research"><div className="section-title"><div><p className="eyebrow">THE BUSINESS BRIEF</p><h2>Here’s what we know so far.</h2><p className="muted">A starting point for a conversation with the owner.</p></div><Compass className="section-icon"/></div><div className="findings">{w.findings.map((f,i)=><article className="finding" key={i}><span className="finding-no">0{i+1}</span><div><div className="finding-label">{f.label}<span className={`pill ${f.status!=='unreviewed'?'green':''}`}>{f.status==='unreviewed'?'Needs confirmation':f.status}</span></div><p>{f.value}</p>{/^https:\/\//.test(f.source)?<a className="source" href={f.source} target="_blank" rel="noreferrer">View source <ArrowUpRight size={13}/></a>:<span className="source">{f.source}</span>}</div></article>)}</div><div className="section-footer"><p className="muted">You know the business. Help the agent get it right.</p><Button onClick={()=>setTab('Calibration')}>Calibrate the brief <ArrowRight size={16}/></Button></div></TabsContent>
 <TabsContent value="Calibration"><div className="section-title"><div><p className="eyebrow">OWNER CHECK-IN</p><h2>What did we get right?</h2><p className="muted">Confirm each finding or edit it. Your corrections guide the plan.</p></div><Hand className="section-icon"/></div><form onSubmit={e=>{e.preventDefault();act('calibrate',{findings,goal,budget,notes},'Channels');}}><div className="calibration-list">{findings.map((f,i)=><div className="calibration" key={i}><label htmlFor={`f${i}`}>{f.label}</label><Textarea id={`f${i}`} value={f.value} onChange={e=>setFindings(fs=>fs.map((x,j)=>i===j?{...x,value:e.target.value,status:'corrected'}:x))}/><Button type="button" variant={f.status==='unreviewed'?'outline':'secondary'} size="sm" onClick={()=>setFindings(fs=>fs.map((x,j)=>i===j?{...x,status:x.value===w.findings[i].value?'confirmed':'corrected'}:x))}><Check size={14}/>{f.status==='unreviewed'?'This is accurate':f.status==='corrected'?'Correction noted':'Confirmed'}</Button></div>)}</div><div className="field-grid"><div><label htmlFor="goal">What outcome matters?</label><Input id="goal" required value={goal} onChange={e=>setGoal(e.target.value)} placeholder="5 qualified calls in 30 days"/></div><div><label htmlFor="budget">Time & budget available</label><Input id="budget" required value={budget} onChange={e=>setBudget(e.target.value)} placeholder="$300 and 4 hours per week"/></div></div><label htmlFor="notes">What else should the agent know?</label><Textarea id="notes" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What has failed before? Any constraints, proof points, or customer insights?"/><div className="section-footer"><p className="muted">{findings.filter(f=>f.status!=='unreviewed').length} of {findings.length} findings reviewed</p><Button disabled={!!busy||findings.some(f=>f.status==='unreviewed')||active.length>0}>Save calibration <ArrowRight size={16}/></Button></div>{active.length>0&&<p className="muted small">Calibration is locked while experiments exist. Start new research for a fresh brief.</p>}</form></TabsContent>
 <TabsContent value="Channels"><div className="section-title"><div><p className="eyebrow">CHOOSE WHERE TO START</p><h2>A few channels. A focused first move.</h2><p className="muted">Run up to two experiments at a time. Targets are hypotheses.</p></div><Radar className="section-icon"/></div>{!w.calibrated?<div className="empty"><Hand/><h3>First, calibrate the research.</h3><p>The owner’s context makes the channel plan useful.</p><Button onClick={()=>setTab('Calibration')}>Review the brief</Button></div>:!w.channels.length?<div className="empty"><Sparkles/><h3>Your brief is ready.</h3><p>Find channels that fit your audience, outcome, and resources.</p><Button disabled={!!busy} onClick={()=>act('plan')}>Suggest channels <ArrowRight size={16}/></Button></div>:<div className="channels">{w.channels.map((c,i)=><article className="channel" key={c.id}><div className="channel-top"><span className="rank">{String(i+1).padStart(2,'0')}</span><span className="pill">{i<2?'Recommended first':'Worth exploring'}</span><span className="small muted">{c.effort}</span></div><h3>{c.name}</h3><p className="muted">{c.rationale}</p><div className="target"><CircleDot size={15}/>{c.target} {c.metric.toLowerCase()}</div><div className="channel-bottom"><p className="small">{c.action}</p><Button variant={i<2?'default':'outline'} disabled={!!busy||c.status!=='suggested'||active.filter(c=>c.status!=='reviewed').length>=2} onClick={()=>act('run',{channel:c.id},'Experiments')}>{c.status==='suggested'?'Create draft':'Started'}<ArrowUpRight size={15}/></Button></div></article>)}</div>}</TabsContent>
 <TabsContent value="Experiments"><div className="section-title"><div><p className="eyebrow">FROM PLAN TO PROGRESS</p><h2>Work you can put into the world.</h2><p className="muted">Review the draft, complete the handoff, then measure the outcome.</p></div><FlaskConical className="section-icon"/></div>{!active.length?<div className="empty"><FlaskConical/><h3>No experiments yet.</h3><p>Pick your first channel to create a reviewable draft.</p><Button onClick={()=>setTab('Channels')}>Explore channels</Button></div>:active.map(c=><article className="experiment" key={c.id}><div className="experiment-title"><h3>{c.name}</h3><span className={`pill ${c.status==='reviewed'?'green':'amber'}`}>{c.status==='needs_owner'?'Your action needed':c.status==='measuring'?'Ready to measure':'Result reviewed'}</span></div><details open><summary>Draft asset <span className="small muted">{w.mode==='demo'?'Demo template':'AI draft · verify before use'}</span></summary><pre>{c.artifact}</pre></details><Button variant="outline" size="sm" onClick={()=>download(`${c.id}-draft.md`,c.artifact||'')}><Download size={14}/>Download draft</Button>{c.status==='needs_owner'&&<div className="handoff"><div className="handoff-title"><Hand size={18}/><strong>Over to you</strong></div><p>{c.handoff}</p><p className="small muted">The MVP creates drafts; posting and sending are owner actions. Your completion log is self-reported.</p><label htmlFor={`e-${c.id}`}>Link or action log</label><Textarea id={`e-${c.id}`} placeholder="Where did you publish, or who did you contact?" value={evidence[c.id]||''} onChange={e=>setEvidence({...evidence,[c.id]:e.target.value})}/><Button disabled={!!busy||(evidence[c.id]||'').trim().length<10} onClick={()=>act('handoff',{channel:c.id,evidence:evidence[c.id]})}>I’ve done this — continue <ArrowRight size={15}/></Button></div>}{c.evidence&&<p className="evidence small"><Check size={15}/>Owner action log: {c.evidence}</p>}{c.status==='measuring'&&<div className="measurement"><h4>What happened?</h4><p className="muted">Target: {c.target} {c.metric.toLowerCase()}. Record results after your experiment window.</p><label htmlFor={`r-${c.id}`}>{c.metric}</label><div className="result-row"><Input id={`r-${c.id}`} type="number" min="0" step="1" value={results[c.id]??''} onChange={e=>setResults({...results,[c.id]:e.target.value})}/><Button disabled={!!busy||!results[c.id]} onClick={()=>act('result',{channel:c.id,result:Number(results[c.id])})}>Review result</Button></div></div>}{c.learning&&<div className="learning"><p className="eyebrow">EXPERIMENT READOUT</p><p>{c.learning}</p></div>}</article>)}</TabsContent>
 </Tabs></section><aside className="context-rail"><div className="rail-card"><p className="eyebrow">THE NORTH STAR</p><h3>{w.goal||'Define your first outcome'}</h3><div className="rail-divider"/><p className="small muted">Resources</p><p>{w.budget||'Set during calibration'}</p><p className="small muted">Operating boundary</p><p className="small">Research and draft creation. You handle external publishing, outreach, and spending.</p></div><div className="rail-card owner-card"><div className="rail-head"><Hand size={17}/><h3>Needs you</h3><span className="count">{waiting.length}</span></div>{waiting.length?waiting.map(c=><button className="queue-item" key={c.id} onClick={()=>setTab('Experiments')}><span>{c.name}<small>Review draft & complete handoff</small></span><ArrowUpRight size={16}/></button>):<p className="small muted">{w.calibrated?'No open handoffs.':'Confirm the business brief to unblock planning.'}</p>}</div><div className="activity"><p className="eyebrow">ACTIVITY</p>{w.log.slice(0,7).map((l,i)=><div className="activity-item" key={i}><span className="activity-dot"/><p>{l.text}<time>{new Date(l.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></p></div>)}</div><Button variant="ghost" size="sm" onClick={()=>download('traction-workspace.json',JSON.stringify(w,null,2))}><Download size={14}/>Export workspace</Button></aside></div></>}
 </main><footer>Traction Lab <span>Research → Calibrate → Experiment → Learn</span></footer></div>;
}
