export type Finding = { label: string; value: string; source: string; status: 'unreviewed' | 'confirmed' | 'corrected' };
export type Channel = { id: string; name: string; rationale: string; effort: string; metric: string; target: number; action: string; handoff: string; status: 'suggested' | 'needs_owner' | 'measuring' | 'reviewed'; artifact?: string; evidence?: string; result?: number; learning?: string };
export type Workspace = { name: string; url: string; mode: 'demo' | 'live'; findings: Finding[]; goal: string; budget: string; notes: string; calibrated: boolean; channels: Channel[]; log: { text: string; at: string }[] };
export function log(w: Workspace, text: string) { w.log.unshift({ text, at: new Date().toISOString() }); }
export function demo(): Workspace { return { name: 'Cedar & Co.', url: 'https://cedar.example', mode: 'demo', goal: 'Book 5 qualified discovery calls in 30 days', budget: '$300 and 4 hours per week', notes: '', calibrated: false, channels: [], log: [{ text: 'Example research loaded. This is a fictional business; no live search was run.', at: new Date().toISOString() }], findings: [
{ label: 'Offer', value: 'Monthly bookkeeping and cash-flow guidance for small creative agencies.', source: 'Fictional demo brief', status: 'unreviewed' },
{ label: 'Ideal customer', value: 'US-based creative agency owners with 5–20 employees.', source: 'Demo assumption — confirm with owner', status: 'unreviewed' },
{ label: 'Differentiation', value: 'Agency-specific reporting and a monthly conversation with a dedicated bookkeeper.', source: 'Fictional demo brief', status: 'unreviewed' },
{ label: 'Current traction', value: 'Most new customers come through founder referrals; other channels are untested.', source: 'Demo assumption — confirm with owner', status: 'unreviewed' }
] }; }
export function validateCalibration(w: Workspace) { if (!w.findings.length || w.findings.some(f => f.status === 'unreviewed' || !f.value.trim())) throw new Error('Review every finding before planning.'); if (!w.goal.trim() || !w.budget.trim()) throw new Error('Add an outcome and resource limit.'); }
export function demoChannels(w: Workspace): Channel[] { const audience = w.findings.find(f=>f.label==='Ideal customer')?.value || 'your ideal customers'; return [
{ id:'outreach', name:'Founder-led outreach', rationale:`A small, targeted conversation test for ${audience}`, effort:'3 hours · $0', metric:'Qualified calls booked', target:5, action:'Create an outreach message and follow-up', handoff:'Choose 10 appropriate contacts, personalize the draft, and send it from your own account. Add a sent log or a brief description of what you sent.' },
{ id:'partners', name:'Referral partnerships', rationale:'Build on the existing referral motion with complementary service providers.', effort:'2 hours · $0', metric:'Partner conversations', target:3, action:'Write a partner invitation and referral offer', handoff:'Choose 5 complementary partners and send the reviewed invitation. Record who you contacted.' },
{ id:'content', name:'Founder content', rationale:'Turn owner expertise into an explicit invitation to start a conversation.', effort:'2 hours · $0', metric:'Qualified inbound conversations', target:3, action:'Draft a practical founder post', handoff:'Review the post for accuracy and publish it on your preferred professional network. Paste the post URL.' },
{ id:'search', name:'Search-led content', rationale:'Test a narrow customer question before investing in a larger content program.', effort:'4 hours · $0', metric:'Qualified inquiries', target:2, action:'Create a search article outline', handoff:'Validate search demand, write and publish the article using the outline. Paste the published URL. Search results may take longer than this first experiment.' },
{ id:'community', name:'Community participation', rationale:'Learn customer language through useful, relevant conversations.', effort:'2 hours · $0', metric:'Customer conversations', target:4, action:'Draft a helpful discussion contribution', handoff:'Find a relevant community, check its rules, adapt the draft, and contribute. Record the community and discussion URL.' }
].map(c=>({...c, status:'suggested'})); }
export function demoArtifact(w: Workspace,c: Channel) { const offer=w.findings[0]?.value || ''; const diff=w.findings[2]?.value || ''; const intro=`DEMO TEMPLATE · Review and personalize before use\n\nBusiness: ${w.name}\nOffer: ${offer}\nGoal: ${w.goal}\nOwner context: ${w.notes || 'None added'}\n\n`; const drafts: Record<string,string> = {
outreach:`Subject: A question about your agency's finances\n\nHi there,\n\nI run ${w.name}. We help with ${offer.charAt(0).toLowerCase()+offer.slice(1)}\n\nHow are you handling this today, and where does it take more time than it should? If it is relevant, I would be happy to compare notes in a short conversation.\n\nFollow-up, after 5 business days:\nOne follow-up on my note. Is this an active priority, or should I leave it here?\n\nBefore sending: add a real recipient name and a verified reason their business fits.`,
partners:`Subject: Could our clients benefit from knowing each other?\n\nI run ${w.name}. ${offer}\n\n${diff}\n\nI would like to understand the kinds of clients you support and see whether there is a useful fit. Would you be open to a brief conversation? No referral arrangement assumed—we can agree terms if there is a fit.`,
content:`A useful question for agency owners: what would make your monthly financial review more useful?\n\nThree things to bring to that conversation:\n• Your current cash position.\n• Upcoming commitments.\n• The decisions you need to make this month.\n\nAt ${w.name}, our work is ${offer.charAt(0).toLowerCase()+offer.slice(1)}\n\nWhat is the one question you wish your reports answered?`,
search:`Working title: A monthly financial review checklist for creative agency owners\n\nReader: ${w.findings[1]?.value}\n\n1. Explain the decision the reader needs to make.\n2. List the documents needed for a monthly review.\n3. Walk through cash, commitments, and open questions.\n4. Add an owner-approved example using real, anonymized information.\n5. Invite readers to discuss their process with ${w.name}.\n\nValidation: confirm demand and competing pages before publication. Do not invent search volume or results.`,
community:`Discussion starter: What do you wish you understood better about your agency's monthly numbers?\n\nI work on ${offer.charAt(0).toLowerCase()+offer.slice(1)} I'd be interested to learn which questions keep coming up for owners here. Happy to share a practical review checklist if helpful.\n\nDisclose your affiliation and follow the community rules. Avoid unsolicited promotion.` }; return intro+drafts[c.id]; }
export function completeHandoff(c: Channel,evidence:string) { if(c.status!=='needs_owner') throw new Error('This experiment is not waiting for an owner action.'); if(evidence.trim().length<10) throw new Error('Add a link or a brief action log (at least 10 characters).'); c.evidence=evidence.trim();c.status='measuring'; }
export function reviewResult(c: Channel,result:number) { if(c.status!=='measuring') throw new Error('Complete the owner action before recording results.'); if(!Number.isInteger(result)||result<0) throw new Error('Enter a non-negative whole number.');c.result=result;c.status='reviewed';c.learning=result>=c.target?`Target met (${result}/${c.target}). Repeat a small test to check whether this result is reproducible before increasing effort.`:`Below target (${result}/${c.target}). Review execution and audience fit, then change one variable for the next test. This result alone does not establish why.`; }
